### ISSUE TITLE
Wykonanie

### ISSUE THREAD

**Issue by Gawinooo** [ProjektZespolowyDGOGPGPA/Raport-klienta-cz.1#1]
@Lamozaur

**Comment by Lamozaur** [comment]
[Proces biznesowy.pdf](https://github.com/ProjektZespolowyDGOGPGPA/Raport-klienta-cz.1/files/164006/Proces.biznesowy.pdf)

**Comment by Gawinooo** [comment]
Do poprawienia jest kwestia tego, że proces biznesowy ma przedstawiać korzyści jakie nasz klient będzie czerpał ze sprzedaży naszego produktu.
